version: '3.8'

services:
  frontend:
    build: . # Esto usará el nuevo Dockerfile en la raíz
    container_name: groupsapp-frontend
    ports:
      - "80:80"
    restart: always
    environment:
      # Ahora la URL se pasa en tiempo de ejecución, no de construcción.
      # En AWS, esto vendría de la configuración de la tarea de ECS o similar.
      - VITE_API_URL=http://34.226.227.26:3000